# 数据源
spring:
  application:
    name: @artifactId@
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://172.19.1.251:3306/yoyo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  shardingsphere:
    datasource:
#      common:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
      names: master
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        ## 使用 lvs 搭建高可用
        jdbc-url: jdbc:mysql://172.19.1.251:3306/yoyo_account?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#      slave: # 直接 slave 123
#        username: root
#        password: root
#        jdbc-url: jdbc:mysql://172.19.1.250:3306/yoyo_account?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    props:
      sql-show: true
    rules:
#      # 读写分离
#      readwrite-splitting:
#        data-sources:
#          yoyo:
#            primary-data-source-name: master
#            replica-data-source-names: slave
#            load-balancers-name: round-robin
#        load-balancers:
#          round-robin:
#            type: ROUND_ROBIN
#            props:
#              workId: 1
      # 分表
      sharding:
        sharding-algorithms:
          tables:
            type: INTERVAL
            props:
              datetime-pattern: yyyy-MM-dd HH:mm:ss
              datetime-lower: 2021-10-01 00:00:00
              datetime-upper: 2099-12-31 00:00:00
              sharding-suffix-pattern: yyyy-MM
              datetime-interval-unit: MONTHS
              datetime-interval-amount: 1
            yoyo_account:
              actual_data_nodes: master.yoyo_account_${2021..2023}-$->{['01','02','03','04','05','06','07','08','09','10','11','12']}
              table-strategy:
                standard:
                  sharding-column: create_time
                  shardong-alorithm-name: table-inline

  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: null
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://172.19.1.251:6379"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 32
          connectionPoolSize: 64
          database: 0
          dnsMonitoringInterval: 5000
        threads: 0
        nettyThreads: 0
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        "transportMode": "NIO"
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: pig-sentinel:5003

# feign 配置
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true

# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: INPUT
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-handlers-package: com.sanyicloud.sanyi.common.mybatis.handler
  type-enums-package: com.sanyicloud
server:
  servlet:
    context-path: /yoyo
